run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - bodyclose
    - errorlint

linters-settings:
  gofmt:
    simplify: true
  errcheck:
    check-type-assertions: false
    check-blank: false
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - bodyclose
  max-issues-per-linter: 0
  max-same-issues: 0
