version: 2
builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.BuildTag={{.Version}} -X main.BuildCommit={{.Commit}} -X main.BuildDate={{.Date}}'
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    binary: '{{ .ProjectName }}'
archives:
  - formats: ['tar.gz']
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    wrap_in_directory: true
    strip_binary_directory: true
    format_overrides:
      - goos: windows
        formats: ['zip']
    files:
      - LICENSE
      - README.md
checksum:
  disable: true

gitea_urls:
  api: https://codeberg.org/api/v1
  download: https://codeberg.org
