apiVersion: v1
kind: Secret
metadata:
    name: cosign-signing-key
    namespace: forgejo-mcp
type: Opaque
stringData:
    cosign.key: ENC[AES256_GCM,data:ck97ep+OvXxo/2mRYeFecU+8PaPTbPdnCQttAsH4yV3SV81XD188jPpoiqjfUpXPJV8qhwT3bSI7p/PNPArWx+gkPagYzMwupBS7C2NkAZ4oMD7Xc9Ow5wr4v4SH1evZ3SdzK7QbClJlW5369sKpOV4uH1NfQLwNNLoT2xQvzQ1NB40g02xri3UAkyEF3lTgOwK5jzf/f3tlxx6cXEnhe3+sRYarh8VvPN4qr7msbsKOHlrjknItrudRisXziludgz4CMRIEMyasz4k+KbshI7UbHQ2YCwLS3tugp+EnoybJCyTva9qytEspH1w7/Hy0b2SaPW3+jIcxoefeyBsQVIFBf+gakJ2+brhXeeaIcn4tI50ZMjWkCu4sRq4TkMKx6/eB6DlrAzyzVC+jiU/wedyC/1xgva2boyhyY8dul4D6RVb2954yyIzyk1LcS9oLcgqW0fbMvBKsij+QfndJnqVwNGmLQOB/++1ZvQvWsAfzx2MUqdgNiUSK7sP33Doeit6KC8lu9HQSHqSDdV5SqCdNYbME/nzZhijXeYwhjOKvJ4eo4zLiZeUJGb/fDYKbnYdIfGpseyIKagriU6I8TAgE6cAprJx6+dNoQZnzmmJg1Hkfmbu7ZGm+HPp/AuqvvTiFdFqcM2k3VzYy7+L664iKmg3qs45fgfyKs/20l5XUZmxbUpUMD/uMDveFEdlKNy/Hvu3TLcD5PkDmGvWO1OY8fu7iqTyaFhbzA/TgO3n0yp9mEIcIGjCtlksW8QuVnw3BhpxAF5JfBH1w5x/NyzD8pjAhz+8TmRWO4rx8XbSqUpszmUx4zGL7INe9RncH8LgWLDcDx1LUpn15YYaQLgmnuDGZvzDQTGDTPGQ=,iv:1KeL4TayhD74hCjp6GWuq1ELPUR4qUk2/15VVbEinh4=,tag:XWNsbO9q2dV9K9lnqfSpcg==,type:str]
    cosign.password: ENC[AES256_GCM,data:MW403F0axLIdqnvb/GoOXA==,iv:OLtkn3bXa6Z1DLlR9P5j17udM6EhYhy6K0Ec/hKeMlE=,tag:QbXMsvQK8vpmeFebttIuGw==,type:str]
    cosign.pub: |
        -----BEGIN PUBLIC KEY-----
        MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEWURZMiQfSUhC9SCarqpQHC9FR38L
        SidTBK1kwSJFdE9SgFXKkH/1T2mTPPU0ZzhA2hVmWkR3RA40fdlAWeW+cw==
        -----END PUBLIC KEY-----
sops:
    lastmodified: "2026-05-24T11:08:02Z"
    mac: ENC[AES256_GCM,data:0dqKKp3RgFIo/9Wmral0TCbKbj4hQEWcLsZ5tPQR6pnj7Shwgz4mjWMKuvjG3SPPE1mwNN9085YoUswqNgvhAwHg91dfWLyspLVWpIknnWxj/fB9CVEZKATs7u+1IgLa0M2nDjzU2lwSj/eOrSZatII0ttSwSLxC+HdASNBpqJk=,iv:ft9fPv3xqnyHjmn34W5YlfjBqjb8eQ6tCxSDI2fcCqg=,tag:1VCTGSVM8G9ZzeM1B1Usug==,type:str]
    pgp:
        - created_at: "2026-05-24T11:08:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9AgVmznaOk7AQ//ZbkFUV3G4HMjWDqxVTBDGPcDks0pgvIx9Qy7PGJUQuTw
            NmUY+TzV6zlkolfNPkkLTCBGVTaS2ZHMlLWwGDbNKCo1o3TLolPb0Rj4eqmXQhJD
            mUbGMX1em6BPhCZJ50pzMtTt5qCuXyRq6g1MyDQtTz2FP0DG1AmjqHAL735ZXoF2
            cK1RXHNrYdaDU2/uWRqjSxhBnV4H+pKxfRNJdP0DJpQXey9JAXnQFLSzPsIwAY/k
            vCHC7fF88Ra8wMxXAbetijKvtZYVQ7TtxARRZgVMv3GlOjdR28mWsTSe0nDdWyKn
            Oz9SbaCAtH+koYUt/vhKCgDBVo5gwjPhyb/T+2TSFWk1rWmPVW9OZqOpAfoy2mED
            6dhrwbRjnWPRNRLiGiDQ2Gu8abbfMLb1czhvceeZuUYm8AxQZsO7aCNvRVu8HS6w
            OoJeDffyJyhTXhvEA7PwLW/m7/2sS3juvoj/w938SCXgxCi8D8Kxwt5xmRVRrQfq
            wG/Kx740eHC8El+5042tANY1BHOXc8oYe+9zxGmacyUZy6rn+5vdqTQ7dDoTuIIW
            hHrs2JvmOUH/LFj90QoPj91VCNAKGgOhcM5RgzCNv5pTfCtf2Ql2J6VBhsCgrSxC
            JD8U4g6boelGCOEafMiWwpy1UntYs+sKYMeYF9LYde7rMjld3mWYI2+yak85BUXS
            XgHeTFeUWHx9hosiVJDOyGspgCEKuzadXlliyEVF2Unjf5KAdoc1DgpiV7se2oXv
            IB1YZVF43KVvkyZmSJYBc7hA7X6+FH/tJZIJ1F/nX0uHUYIWPRfQ8piiVhD3Gx4=
            =Z8cN
            -----END PGP MESSAGE-----
          fp: 04DAFCD9470A962A2F272984E5EB0DA32F3372AC
        - created_at: "2026-05-24T11:08:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSHi8yuDIZWAQ/+KP1TGPMd3pnqmpSCTPyEYpboI7lEekwYj8z+Kp2mqoqf
            pVR04Wh72gE+IaYTOeinOuksLMhX7AW9CWJX0vTgWiqcxZzp+t8ImhtRWd31LwZd
            aiw3HbbhH4gddDIpyP54PIEYwDiuo3FRRjBZT1osT6TtN9UPRft6M8/4DIef3KVX
            FPgQKl0DqQ4H3nC6sE6/F82XNmwMrNi1hSPrvJxKks/Nxs/u+j+OtVeCy6n5LPDY
            JrZh75Q8q1Q0180j5PA/4zySEhJ+SyihoZJDYn0SSmASrVRWdWZs1F4PQGbYYFzD
            8dV6gw/T7lDEIJK46WsnKkaP1dIf31WBD80lEM3d4QNDwcDTsJEU+a3spc2Zouww
            9u9xJh/XrkYZ5W+pYPLoBpGG5fMBYXDNZTq2UKND05MiSC++43xEGnj0LPx8fn/c
            IZMh7NimlJt9Xl+OFnxRXQcyLzdFqCeGWBziEvwzR1qQiGclgnZuJybObR8HwJ7l
            QwY4lKqD+GvL8uvtFtFi14mqAb6Q1DmROEl1wdjyHoUNa2eBusrDd5DQXtSH5jQ+
            QJ2VBJsLzTZU9p2MpezncOQixU/RegwFbIcY6li8IHLDW7M0IhEUDsE+JP19SULD
            5kg0D4QsvDI12R7665qYhST9mH8aHJUKL2gV7MAUfGRP8seCXTX6bE4Z6wosqYjS
            XgEFqz/FSqXljtW5em1z3WKm0vvW5VEBGC7u1zfohWlkvGzxV9YiucI7rreVxnnc
            sx2zcwdARbQrW754zx90SATmuprBy/6ukzH6g8Tz2xIszO2JK7quZxLlA8VtxYs=
            =kCBh
            -----END PGP MESSAGE-----
          fp: 8A07D816280A983BBC35E85C280DB66A3E8C012E
    encrypted_regex: ^(cosign\.key|cosign\.password)$
    version: 3.12.1
